name: Pruebas unitarias de la base de datos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: universidad
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4      

      - name: Wait for PostgreSQL to be ready
        run: until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Cargar esquema de la base de datos
        run: |
          psql -h localhost -U postgres -d universidad -f schema.sql
        env:
          PGPASSWORD: postgres

      - name: Insertar datos de prueba
        run: |
          psql -h localhost -U postgres -d universidad -f data.sql
        env:
          PGPASSWORD: postgres          

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-csv psycopg2-binary

      - name: Run tests and save results
        run: |
          pytest test_functional.py
        continue-on-error: true
        env:
          PGPASSWORD: postgres          
  
      - name: Commit and push test results to results branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b results || git checkout results
          git pull origin results
          git add results.csv
          git commit -m 'Update test results'
          git push origin results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}          
